var R=[
  {n:"180g Pizzeria Romana",a:"Via Tor Millina 15, Navona",pl:2,pr:"€€ · ~25€",cu:"Pizza Romana",tg:"pizza",ws:"https://www.180grammi.it/",st:"La migliore pizza tonda romana di nuova generazione. Impasto a 72 ore, farine artigianali. 50 Top Pizza. Jacopo Mercuro maestro della tonda romana.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["La pizza tonda romana qui raggiunge la sua forma piu compiuta: sottile, croccante, fragrante.","Jacopo Mercuro ha fatto capire a Roma e al mondo cosa puo essere la pizza romana.","Il locale e piccolo ma ben organizzato: la fila scorre veloce."]},
  {n:"Acciuga",a:"Via Vodice 25, Prati",pl:3,pr:"€€€ · ~70€",cu:"Alta Cucina di Mare",tg:"pesce",ws:"https://acciugaroma.it/",st:"Chef Federico Delmonte porta il pescato dell Adriatico a Prati. Cucina di mare povera e nobile: pesce di piccola pezzatura, menu degustazione che cambia con il mercato. Nella guida Michelin.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Il pescato cambio ogni giorno: la cucina parla con il mercato e non il contrario.","Il brodetto fanese e un omaggio alle origini marchigiane dello chef: commovente.","Una delle cucine di mare piu interessanti di Roma. Menu degustazione obbligatorio."]},
  {n:"Achilli al Parlamento",a:"Via dei Prefetti 15, Centro Storico",pl:4,pr:"€€€€ · ~100€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.enotecaachilli.com/",st:"Una stella Michelin vicino al Parlamento. Enoteca storica trasformata in ristorante d autore. Cucina italiana di territorio con cantina eccezionale.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:16,l:"16/20"},rv:["Enoteca storica con oltre 1000 etichette: un paradiso per gli amanti del vino.","La cucina italiana e solida e rispettosa del territorio: abbinamenti precisi e intelligenti.","La posizione vicino al Pantheon non ha eguali."]},
  {n:"Acquolina",a:"Via dell'Ara Coeli 3, Centro Storico",pl:5,pr:"€€€€€ · ~180€",cu:"Alta Cucina di Mare",tg:"pesce",ws:"https://www.thefirstroma.it/it/ristoranti/acquolina/",st:"Due stelle Michelin. Chef Daniele Lippi al The First Roma Arte Hotel. Cucina di mare d autore con ingredienti selezionati e tecnica raffinata.",mi:{s:2,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:18,l:"18/20"},rv:["Il crudo di pesce e di una qualita eccezionale: materia prima impeccabile.","Menu degustazione visionario che racconta il mare con poesia e rigore tecnico.","Tra i migliori ristoranti di pesce d Italia."]},
  {n:"Aiki",a:"Via Gaetano Rappini 23c, Prati",pl:2,pr:"€€ · ~40€",cu:"Giapponese Izakaya",tg:"giapponese",ws:"https://www.instagram.com/aiki_pub_roma/",st:"Izakaya autentica a Prati. La sera osteria giapponese con yakitori, okonomiyaki, sake e birre nipponiche. Il pomeriggio sala da te con dolci giapponesi come dorayaki e mochi.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Una delle izakaya piu autentiche di Roma: atmosfera da osteria giapponese vera.","Il pomeriggio si trasforma in sala da te con dolci tradizionali: un format unico nella Capitale.","Yakitori, okonomiyaki e sake a prezzi onesti: difficile trovare di meglio a Prati."]},
  {n:"All'Oro",a:"Via Giuseppe Pisanelli 25, Prati",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina Creativa",tg:"italiana",ws:"https://www.ristorantealloro.it/",st:"Una stella Michelin. Chef Riccardo Di Giacinto. Cucina creativa italiana con ingredienti del territorio laziale.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["La carbonara rivisitata e un capolavoro di tecnica e rispetto per la tradizione.","Carta dei vini eccellente, servizio impeccabile.","Tra i migliori indirizzi della Roma contemporanea."]},
  {n:"Armando al Pantheon",a:"Salita dei Crescenzi 31, Centro Storico",pl:2,pr:"€€ · ~45€",cu:"Romana Tradizionale",tg:"italiana",ws:"https://armandoalpantheon.it/",st:"Trattoria storica dal 1961 alle spalle del Pantheon. Famiglia Gargioli. Cucina romana autentica: carbonara, coda alla vaccinara, coratella, abbacchio. Tre Gamberi Gambero Rosso. Nella guida Michelin.",mi:{s:0,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:16,l:"16/20"},rv:["Dal 1961 il punto di riferimento per la vera cucina romana vicino al Pantheon.","La coda alla vaccinara e il quinto quarto sono eseguiti con cura rarissima a Roma.","Prenotare con settimane di anticipo: e uno dei tavoli piu ambiti della Capitale."]},
  {n:"Aroma",a:"Via Labicana 125, Celio",pl:5,pr:"€€€€€ · ~150€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.aromarestaurant.it/",st:"Una stella Michelin. Sul tetto del Palazzo Manfredi, con vista sul Colosseo. Chef Giuseppe Di Iorio.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["La vista sul Colosseo e unica al mondo: si mangia di fronte al monumento piu famoso di Roma.","Cucina italiana elegante e ben eseguita, degna della location straordinaria.","Il risotto al pecorino con guanciale croccante e uno dei piatti piu riusciti."]},
  {n:"Baccano",a:"Via delle Muratte 23, Fontana di Trevi",pl:3,pr:"€€€ · ~55€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://baccanoroma.com/",st:"Bistrot moderno vicino alla Fontana di Trevi. Cucina italiana contemporanea dalla colazione alla cena, ottima carta dei vini e cocktail bar.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Uno dei pochi posti vicino ai monumenti dove si mangia davvero bene.","La pasta fresca e la charcuterie sono di ottima qualita.","Cocktail bar di livello con bartender preparati."]},
  {n:"Bistrot 64",a:"Via Guglielmo Calderini 64, Flaminio",pl:4,pr:"€€€€ · ~85€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.bistrot64.it/",st:"Ristorante gourmet nel quartiere Flaminio. Chef Giacomo Zezza. Alta cucina italiana stagionale con menu degustazione da 70 e 95 euro. Nella guida Michelin.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Chef Zezza costruisce piatti di grande personalita: cucina tecnica senza rigidita.","Il menu degustazione da 70 euro e uno dei migliori rapporti qualita del prezzo a Roma.","Il quartiere Flaminio non scoraggia i romani: il locale e sempre pieno."]},
  {n:"Borghese Gallery Restaurant",a:"Viale del Museo Borghese 5, Parioli",pl:4,pr:"€€€€ · ~90€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.borgheserestaurant.com/",st:"Ristorante all'interno della Galleria Borghese. Cucina italiana contemporanea con terrazza sul parco di Villa Borghese.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Mangiare nel parco piu bello di Roma con vista sulla Galleria Borghese: esperienza unica.","La cucina italiana e di buon livello, all altezza della straordinaria location.","Il brunch domenicale e tra i piu esclusivi della citta."]},
  {n:"Checchino dal 1887",a:"Via di Monte Testaccio 30, Testaccio",pl:3,pr:"€€€ · ~65€",cu:"Romana Tradizionale",tg:"italiana",ws:"https://www.checchino-dal-1887.com/",st:"Storico ristorante di cucina romana dal 1887 nel cuore di Testaccio. Coda alla vaccinara, pajata, trippa. Cantina nel Monte Testaccio.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["La coda alla vaccinara e il piatto piu autentico della cucina romana: qui e perfetta.","Cantina leggendaria scavata nel tufo del Monte Testaccio.","Un istituzione di Roma: 140 anni di storia."]},
  {n:"Cocta Risto Social Club",a:"Via del Casale Rocchi 6, Pietralata",pl:2,pr:"€€ · ~45€",cu:"Italiana Creativa",tg:"italiana",ws:"https://cocta.it/",st:"Social club e ristorante a Pietralata. Chef Stefano Garonna ex Il Pagliaccio e Orma. Cucina creativa, tavoli conviviali, cocktail bar, terrazza.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Chef Garonna porta la sua esperienza stellata in un contesto informale e riuscito.","I tavoli conviviali da 8-10 persone sono un format unico a Roma.","La terrazza e il cocktail bar lo rendono perfetto dall aperitivo fino a notte fonda."]},
  {n:"Colline Emiliane",a:"Via degli Avignonesi 22, Barberini",pl:2,pr:"€€ · ~40€",cu:"Emiliana",tg:"italiana",ws:"https://www.collineemiliane.it/",st:"Trattoria emiliana dal 1931 a Roma. Tortellini in brodo fatti a mano, tagliatelle al ragu, cotechino. Artigianato culinario emiliano.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["I tortellini in brodo sono probabilmente i migliori di Roma: pasta tirata a mano ogni giorno.","Una trattoria vera, senza fronzoli, dove si mangia come a Bologna.","Prezzi onesti per una qualita che non teme confronti."]},
  {n:"Cresci",a:"Via Alcide de Gasperi 11, Prati",pl:2,pr:"€€ · ~30€",cu:"Pizza in Teglia",tg:"pizza",ws:"https://www.cresciroma.it/",st:"Forno, pizzeria, osteria e cocktail bar aperto dalla mattina a mezzanotte. Chef Danilo Frisone. Pizza in teglia a lievitazione naturale. 50 Top Pizza. Due passi dal Vaticano.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:14,l:"14/20"},rv:["La pizza in teglia di Frisone e tra le piu buone di Roma: alveolata, fragrante, digeribile.","Un locale versatile dalla colazione all aperitivo: un formato raro e riuscito.","Il pane artigianale e i lievitati sono di livello eccezionale."]},
  {n:"Da Enzo al 29",a:"Via dei Vascellari 29, Trastevere",pl:2,pr:"€€ · ~35€",cu:"Romana Tradizionale",tg:"italiana",ws:"https://daenzoal29.com/",st:"Trattoria romana autentica a Trastevere. Carbonara, cacio e pepe, trippa alla romana. Uno dei posti piu amati dai romani.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La carbonara piu discussa e amata di Roma: crema d uovo densa, guanciale croccante.","Ambiente informale e genuino: ci si siede vicini, si chiacchiera con i vicini.","La lista di attesa vale sempre la pena."]},
  {n:"Dal Bolognese",a:"Piazza del Popolo 1, Flaminio",pl:4,pr:"€€€€ · ~80€",cu:"Emiliana",tg:"italiana",ws:"https://www.dalbolognese.it/",st:"Storico ristorante di cucina bolognese sulla magnifica Piazza del Popolo. Dal 1940, frequentato da artisti e intellettuali.",mi:{s:0,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:15,l:"15/20"},rv:["La terrazza su Piazza del Popolo e una delle location piu belle della ristorazione romana.","La cucina bolognese e eseguita con rispetto e qualita degli ingredienti.","Un pezzo di storia di Roma: Fellini, Warhol, i Berlinguer hanno mangiato qui."]},
  {n:"El Porteno Roma",a:"Largo del Teatro Valle 7, Navona",pl:3,pr:"€€€ · ~70€",cu:"Argentina",tg:"internazionale",ws:"https://www.elporteno.it/teatro-valle/",st:"Il tempio dell asado argentino nel cuore di Roma, vicino al Pantheon. Carne argentina alla parrilla, empanadas, vini sudamericani.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La carne argentina alla parrilla e tra le migliori di Roma: tenera e saporita.","Le empanadas sono un classico imperdibile: calde e fragranti.","L atmosfera da Buenos Aires al centro di Roma e perfettamente riuscita."]},
  {n:"Enoteca La Torre",a:"Lungotevere delle Armi 22, Prati",pl:5,pr:"€€€€€ · ~170€",cu:"Alta Cucina Creativa",tg:"italiana",ws:"https://www.enotecalatorre.com/",st:"Due stelle Michelin a Villa Laetitia. Chef Domenico Stile. Alta cucina creativa in una villa dei primi del 900 con giardino.",mi:{s:2,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:18,l:"18/20"},rv:["Cucina di ricerca tra le piu interessanti di Roma: ogni piatto e un racconto.","La villa e il giardino creano un atmosfera unica.","Carta dei vini da 3000 etichette: il paradiso per gli appassionati."]},
  {n:"Flavio al Velavevodetto",a:"Via di Monte Testaccio 97, Testaccio",pl:2,pr:"€€ · ~38€",cu:"Romana Tradizionale",tg:"italiana",ws:"https://velavevodetto.it/",st:"Osteria romana storica scavata nel Monte Testaccio. Cucina della tradizione capitolina senza compromessi.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["L ambiente e unico: si mangia dentro il Monte Testaccio tra le anfore romane.","La trippa alla romana e gli spaghetti cacio e pepe sono tra i migliori di Roma.","Uno dei luoghi piu autentici della cucina popolare romana."]},
  {n:"Giulio Passami l'Olio",a:"Via di Monte Giordano 28, Navona",pl:2,pr:"€€ · ~35€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.giuliopassamilolio.it/",st:"Bistrot informale vicino a Piazza Navona. Cucina italiana con ottima selezione di oli extravergine e vini naturali.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Gli oli extravergine sono il filo conduttore di tutta la cucina: una scelta identitaria riuscita.","Vicino a Piazza Navona ma senza essere una trappola per turisti.","Atmosfera informale e prezzi onesti: un posto dove tornare."]},
  {n:"Glass Hostaria",a:"Vicolo del Cinque 58, Trastevere",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina Creativa",tg:"italiana",ws:"https://www.glasshostaria.it/",st:"Una stella Michelin a Trastevere. Chef Cristina Bowerman. Cucina creativa di ricerca in un ambiente di design minimalista.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Cristina Bowerman e una delle chef piu interessanti d Italia: cucina personale e coraggiosa.","Il design dell ambiente e il contrasto piu bello di Trastevere.","Menu degustazione tra i piu originali della scena romana."]},
  {n:"Golino's",a:"Via Francesco Bolognesi 8, Gianicolense",pl:3,pr:"€€€ · ~55€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.gamberorosso.it/luoghi/locali/bistrot/golinos-boutique-bistrot/",st:"Boutique bistrot dello chef Andrea Golino (noto al pubblico del Gambero Rosso). Cucina italiana contemporanea in un ambiente intimo con cucina a vista. Pochi coperti, grande cura.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Il bistrot di Andrea Golino e un gioiellino: ogni piatto racconta una storia personale.","Cucina a vista e chef presente in sala: un format che funziona alla perfezione.","Gli spaghetti all assassina sono leggendari: da soli valgono la prenotazione."]},
  {n:"Grano",a:"Piazza Rondanini 53, Centro Storico",pl:3,pr:"€€€ · ~55€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.granoroma.com/",st:"Ristorante contemporaneo vicino al Pantheon. Cucina italiana con ottima selezione di vini naturali e atmosfera informale.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Uno dei pochi posti vicino al Pantheon dove si mangia con qualita senza pagare il conto del turismo.","Vini naturali selezionati con intelligenza, cucina di stagione ben eseguita.","Atmosfera rilassata e conviviale: si torna volentieri."]},
  {n:"Hasekura",a:"Via dei Serpenti 27, Monti",pl:3,pr:"€€€ · ~60€",cu:"Giapponese Tradizionale",tg:"giapponese",ws:"https://www.hasekura.it/",st:"Dal 1993 nel Rione Monti, il ristorante giapponese piu storico di Roma. Fondato da Kimiji Ito. Sushi, sashimi, sukiyaki e soba di altissima qualita. Segnalato dalla guida Michelin.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Il ristorante giapponese piu autentico di Roma dal 1993: qualita immutata.","Il sashimi e il sushi sono eseguiti con materie prime eccellenti e tecnica impeccabile.","Frequentato dalla comunita giapponese di Roma: la migliore raccomandazione possibile."]},
  {n:"Hiromi La Terrazza",a:"Via Agostino Depretis 77, Monti",pl:3,pr:"€€€ · ~65€",cu:"Giapponese Contemporanea",tg:"giapponese",ws:"https://hiromi.it/",st:"Rooftop giapponese del gruppo Hiromi sul 77 Hotel nel rione Monti. Sushi a vista, area tatami, sake bar e terrazza con vista su Santa Maria Maggiore. Aperto nel 2026.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Sopra i tetti di Monti con vista sulla Basilica di Santa Maria Maggiore: un indirizzo che sorprende.","Il sushi counter a vista e il bancone del sake sono il cuore del locale: tecnica e qualita elevate.","L area tatami per cene tradizionali giapponesi e una rarissima opportunita a Roma."]},
  {n:"Idylio by Apreda",a:"Via della Rotonda 69, Centro Storico",pl:5,pr:"€€€€€ · ~160€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.thepantheonhotel.com/it/ristorante/",st:"Una stella Michelin al The Pantheon Iconic Rome Hotel. Chef Francesco Apreda. Alta cucina italiana con influenze internazionali.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Il risotto ai profumi di Napoli e uno dei piatti signature di Apreda: tecnica impeccabile.","L hotel e una delle dimore piu eleganti di Roma.","Cucina che unisce le radici partenopee dello chef con anni di esperienze internazionali."]},
  {n:"Il Convivio Troiani",a:"Vicolo dei Soldati 31, Navona",pl:5,pr:"€€€€€ · ~140€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.ilconviviotroiani.com/",st:"Una stella Michelin vicino a Piazza Navona. I fratelli Troiani dal 1990. Cucina italiana classica e contemporanea.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["I fratelli Troiani sono una delle famiglie piu importanti della ristorazione romana.","La lombata di agnello laziale con crosta di erbe e il secondo piatto di riferimento.","Cantina straordinaria con verticali di Barolo e Brunello."]},
  {n:"Il Pagliaccio",a:"Via dei Banchi Vecchi 129, Campo de' Fiori",pl:5,pr:"€€€€€ · ~200€",cu:"Alta Cucina Creativa",tg:"italiana",ws:"https://ristoranteilpagliaccio.com/",st:"Due stelle Michelin. Chef Anthony Genovese. La cucina piu coraggiosa e sperimentale di Roma con influenze asiatiche.",mi:{s:2,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:19,l:"19/20"},rv:["Anthony Genovese e probabilmente il miglior chef di Roma: cucina che non smette di stupire.","Il menu degustazione e un viaggio tra Europa, Asia e Medio Oriente.","Uno dei ristoranti piu importanti d Italia."]},
  {n:"Il Sorpasso",a:"Via Properzio 31, Prati",pl:2,pr:"€€ · ~32€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.ilsorpassoroma.it/",st:"Bar bistrot di Prati dalla mattina alla sera. Cucina italiana informale di qualita, ottimi panini e taglieri, aperitivo curato.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Dalla colazione alla cena: uno dei locali piu versatili di Roma.","I panini con salumi e formaggi selezionati sono un riferimento nel quartiere Prati.","Ambiente sempre animato e piacevole."]},
  {n:"Imago",a:"Piazza della Trinita dei Monti 6, Spagna",pl:5,pr:"€€€€€ · ~160€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.hotelhasslerroma.com/it/imago",st:"Una stella Michelin all'Hotel Hassler. Chef Andrea Antonini. Terrazza con vista panoramica sui tetti di Roma.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["La vista da Imago e la piu bella di Roma: al tramonto non ha rivali al mondo.","Chef Antonini porta una cucina italiana contemporanea di grande eleganza.","Il risotto alla Romanesca e il piatto che racconta meglio l identita del locale."]},
  {n:"INEO",a:"Piazza della Repubblica 47, Repubblica",pl:5,pr:"€€€€€ · ~150€",cu:"Alta Cucina Creativa",tg:"italiana",ws:"https://www.anantara.com/it/palazzo-naiadi-rome/restaurants/ineo",st:"Una stella Michelin 2026 all'Anantara Palazzo Naiadi. Chef Heros De Agostinis. Alta cucina contemporanea in una location iconica.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Nuova stella Michelin 2026: cucina di grande personalita in un hotel di lusso.","La terrazza con vista sulle Terme di Diocleziano e mozzafiato.","Chef De Agostinis porta un linguaggio gastronomico originale e contemporaneo."]},
  {n:"L Antico Arco",a:"Piazzale Aurelio 7, Gianicolo",pl:4,pr:"€€€€ · ~90€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://anticoarco.it/",st:"Dal 1996 in cima al Gianicolo con vista su Roma. Chef Fundim Gjepali. Cucina italiana creativa con ingredienti selezionati. Cantina da 1200 etichette. Segnalato dalla guida Michelin.",mi:{s:0,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:16,l:"16/20"},rv:["La posizione sul Gianicolo con vista su Roma e gia un motivo sufficiente per venire.","Chef Gjepali porta una prospettiva balcanica sulla cucina italiana: risultato originale.","La cantina da 1200 etichette e una delle piu interessanti di Roma."]},
  {n:"L Arcangelo",a:"Via Giuseppe Gioacchino Belli 59, Prati",pl:3,pr:"€€€ · ~55€",cu:"Romana Tradizionale",tg:"italiana",ws:"https://www.larcangelo.com/",st:"Osteria gourmet di Arcangelo Dandini nel cuore di Prati. Cucina romana e laziale con ingredienti selezionati e tecnica raffinata. Nella guida Michelin e Gambero Rosso.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Arcangelo Dandini e una delle voci piu autorevoli della cucina romana contemporanea.","I supplì e i primi della tradizione laziale sono eseguiti con una cura rara.","Cantina con vini a mescita selezionati con intelligenza: non solo laziali."]},
  {n:"La Gatta Mangiona",a:"Via Federico Ozanam 30, Monteverde",pl:2,pr:"€€ · ~30€",cu:"Pizza Napoletana",tg:"pizza",ws:"https://www.lagattamangiona.com/",st:"Pizzeria storica di Monteverde. Impasto con lievito madre, farine macinate a pietra. Tra le migliori pizzerie di Roma.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Il cornicione e il piu fragrante di Roma: alveolato, croccante fuori e morbido dentro.","La pizza alla zucca gialla con provola affumicata e insolita e perfetta.","Prenotare con settimane di anticipo: ne vale sempre la pena."]},
  {n:"La Menagere",a:"Via Mario de Fiori 99, Spagna",pl:3,pr:"€€€ · ~60€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.lamenagereroma.com/",st:"Branch romana del concept fiorentino in via de Fiori. Ristorante, cocktail bar e flower shop nel cuore di Roma. Cucina italiana contemporanea.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Il concept fiorentino sbarca a Roma con successo: ambiente unico tra ristorante e galleria.","Cucina italiana contemporanea in un contesto di design raffinato.","Ottima scelta per brunch e aperitivo in una delle vie piu eleganti di Roma."]},
  {n:"Luna by Faro",a:"Via delle Quattro Fontane 175, Barberini",pl:2,pr:"€€ · ~40€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.lunabyfaro.it/",st:"Il ristorante del gruppo Faro, prima specialty coffee di Roma. Chef Leonardo Santucci. Brunch internazionale, trattoria contemporanea, vini biologici e naturali.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:14,l:"14/20"},rv:["Il gruppo Faro porta la sua etica del specialty coffee anche in cucina.","Il brunch e tra i piu interessanti di Roma: cucina internazionale con ingredienti locali.","Vini solo biologici e naturali: una scelta coerente e non scontata."]},
  {n:"Maccheroni",a:"Piazza delle Coppelle 44, Centro Storico",pl:2,pr:"€€ · ~35€",cu:"Romana Tradizionale",tg:"italiana",ws:"https://ristorantemaccheroni.com/",st:"Trattoria romana storica vicino al Pantheon. Cacio e pepe, amatriciana, abbacchio alla romana. Frequentata dai romani.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["L'amatriciana e quella vera: guanciale di Amatrice, pelati San Marzano, pecorino romano.","Un miracolo: cucina autentica a due passi dal Pantheon senza pagare prezzi da turista.","I romani vengono qui: e la migliore raccomandazione possibile."]},
  {n:"Marco Martini Restaurant",a:"Viale Aventino 121, Aventino",pl:5,pr:"€€€€€ · ~120€",cu:"Alta Cucina Creativa",tg:"italiana",ws:"https://www.marcomartinirestaurant.com/",st:"Una stella Michelin sull'Aventino. Chef Marco Martini. Cucina creativa italiana con forti radici laziali.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:16,l:"16/20"},rv:["Marco Martini e uno degli chef piu interessanti della nuova Roma.","Il piccione al ginepro con cicoria e pecorino e il piatto che lo ha reso famoso.","Sull Aventino, lontano dal centro turistico: un indirizzo per intenditori."]},
  {n:"Metamorfosi",a:"Via Giovanni Antonelli 30, Parioli",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina Creativa",tg:"italiana",ws:"https://www.metamorfosiroma.it/",st:"Una stella Michelin ai Parioli. Chef Roy Caceres. Cucina di ricerca con influenze internazionali.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Roy Caceres e uno dei cuochi piu originali di Roma: cucina che si evolve sempre.","Il menu degustazione e una sfida e un piacere: non si sa mai cosa aspettarsi.","Ai Parioli, lontano dal turismo: un indirizzo per chi cerca qualcosa di diverso."]},
  {n:"Mikachan",a:"Via Torcegno 39, Infernetto",pl:3,pr:"€€€ · ~55€",cu:"Giapponese Tradizionale",tg:"giapponese",ws:"https://www.instagram.com/mikachan_ristorante_giapponese/",st:"L izakaya piu imprenotabile di Roma all Infernetto. Chef e sushi master Micaela Giambanco, formata in Giappone. Pochi coperti, cucina tradizionale autentica: sushi, ramen, donburi. Lista d attesa di settimane.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Il ristorante giapponese piu autentico di Roma: Micaela Giambanco ha studiato in Giappone ed e sushi master premiata.","Pochi coperti, prenotazione di settimane: ne vale ogni minuto di attesa.","Dai donburi ai ramen agli stufati: cucina tradizionale giapponese rarissima a Roma."]},
  {n:"Moma",a:"Via San Basilio 42, Barberini",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.moma-restaurant.com/",st:"Una stella Michelin vicino a Via Veneto. Chef Salvatore Tassa. Cucina italiana di ricerca con forte identita laziale.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:16,l:"16/20"},rv:["Le castagne di Vallerano e il piatto piu celebre di Salvatore Tassa: semplice e indimenticabile.","Un ristorante che ha saputo costruire una propria identita forte e riconoscibile.","La mise en place essenziale riflette la filosofia del menu: niente di superfluo."]},
  {n:"Ninu",a:"Via della Frezza 43, Centro Storico",pl:3,pr:"€€€ · ~65€",cu:"Pesce Contemporaneo",tg:"pesce",ws:"https://ninuroma.com/",st:"Ristorante di pesce con cocktail bar e B&B. Chef Marco Gallotta. Pesce freschissimo, crudi, ceviche. Dehors su via della Frezza vicino all Ara Pacis.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Via della Frezza e tra le strade piu belle del centro: il dehors di Ninu e perfetto.","Chef Gallotta ha una lunga esperienza con il mare: il pesce e freschissimo ogni giorno.","Il cannellone di baccala e il pacchero con polpo sono i piatti piu amati dai clienti."]},
  {n:"Orma Roma",a:"Via dei Cerchi 55, Aventino",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.ormarestaurant.it/",st:"Una stella Michelin al Circo Massimo. Chef Roy Caceres. Cucina italiana con influenze colombiane: uno dei ristoranti piu originali di Roma.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Roy Caceres porta un punto di vista colombiano sulla cucina italiana: risultato straordinario.","La vista sul Circo Massimo e unica.","Un ristorante che non assomiglia a nessun altro di Roma."]},
  {n:"Osteria dell'Anima",a:"Via di Santa Maria dell'Anima 26, Navona",pl:3,pr:"€€€ · ~50€",cu:"Romana Contemporanea",tg:"italiana",ws:"https://www.osteriadellanima.it/",st:"Osteria contemporanea vicino a Piazza Navona. Cucina romana rivisitata con materie prime eccellenti e vini naturali.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La cucina romana qui non ha paura di innovare: tradizione e creativita in equilibrio.","Selezione di vini naturali tra le piu curate del centro storico.","Vicino a Piazza Navona ma con prezzi e qualita che non tradiscono."]},
  {n:"Osteria Fernanda",a:"Via Crescenzio 55, Prati",pl:3,pr:"€€€ · ~55€",cu:"Romana Contemporanea",tg:"italiana",ws:"https://osteriafernanda.com/",st:"Osteria contemporanea a Prati. Cucina romana aggiornata con ingredienti di qualita e vini naturali.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["La cucina romana contemporanea trova qui uno degli indirizzi piu riusciti.","Vini naturali selezionati con intelligenza: la carta e un viaggio tra piccoli produttori.","Atmosfera informale e piacevole: si torna volentieri."]},
  {n:"Pascucci al Porticciolo",a:"Via Fiumara 2, Fiumicino",pl:4,pr:"€€€€ · ~100€",cu:"Alta Cucina di Mare",tg:"pesce",ws:"https://www.ristorantepascucci.it/",st:"Una stella Michelin a Fiumicino. Chef Gianfranco Pascucci. Il miglior ristorante di pesce dell'area romana.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Il miglior pesce dell area romana: Pascucci conosce ogni pescatore del Tirreno.","La zuppa di pesci e crostacei e un patrimonio immateriale della cucina laziale.","Vale il viaggio fino a Fiumicino: uno dei migliori ristoranti di pesce d Italia."]},
  {n:"Per Me Giulio Terrinoni",a:"Vicolo del Malpasso 9, Campo de' Fiori",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina di Mare",tg:"pesce",ws:"https://perme-roma.it/",st:"Una stella Michelin vicino a Campo de Fiori. Chef Giulio Terrinoni. Cucina di mare italiana con tecnica raffinata.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Il crudo di mare e la specialita di Terrinoni: pesce freschissimo con abbinamenti insoliti.","Uno dei migliori ristoranti di pesce di Roma.","L ambiente raccolto crea un intimita perfetta per cene speciali."]},
  {n:"Pianostrada",a:"Via delle Zoccolette 22, Trastevere",pl:2,pr:"€€ · ~38€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://pianostrada.it/",st:"Bistrot contemporaneo a Trastevere, fondato da quattro donne. Cucina italiana con ingredienti bio. Ottima colazione e brunch.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:14,l:"14/20"},rv:["Fondato da quattro donne: una storia di successo nella ristorazione romana.","I dolci e la pasticceria sono di qualita eccezionale: la crostata al limone e leggendaria.","Il brunch del weekend e tra i migliori di Roma."]},
  {n:"Pipero Roma",a:"Corso Vittorio Emanuele II 250, Centro Storico",pl:5,pr:"€€€€€ · ~140€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.piperoroma.it/",st:"Una stella Michelin sul Corso Vittorio Emanuele. Chef Ciro Scamardella. Alessandro Pipero in sala: il miglior maitre d Italia.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Alessandro Pipero e il maitre piu famoso d Italia: l esperienza in sala e straordinaria.","La carbonara di Ciro Scamardella e una delle migliori versioni gourmet esistenti.","Un ristorante che vale per la cucina e per il servizio in egual misura."]},
  {n:"Pulejo",a:"Lungotevere Mellini 11, Prati",pl:5,pr:"€€€€€ · ~120€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.pulejo.com/",st:"Una stella Michelin sul Lungotevere. Chef Francesco Sposito. Cucina italiana contemporanea con radici campane. Terrazza sul Tevere.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["La terrazza sul Tevere e tra le location piu belle della nuova ristorazione romana.","Chef Sposito porta la sua formazione campana in una cucina italiana elegante e moderna.","Un indirizzo giovane e di grande qualita."]},
  {n:"QUID",a:"Piazza San Silvestro 8, Centro Storico",pl:5,pr:"€€€€€ · ~175€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://quidrome.com/",st:"Aperto maggio 2026. Enrico Bartolini e chef Juan Camilo Quintero sul rooftop di Palazzo Marignoli. Vista panoramica su Roma.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:15,l:"15/20"},rv:["L apertura piu attesa del 2026: Bartolini porta la sua visione nella Capitale.","Il rooftop di Palazzo Marignoli e tra le viste piu belle di Roma.","Juan Quintero porta la sua stella Michelin: cucina di grande livello."]},
  {n:"Rame",a:"Via Folco Portinari 33, Gianicolense",pl:3,pr:"€€€ · ~60€",cu:"Sushi Italiano",tg:"giapponese",ws:"https://www.instagram.com/rame.sushi/",st:"Rame Sushi Naturale Italiano dello chef Alessandro Basciu. Fusion tra tecnica giapponese e ingredienti italiani. Senza glutine. Terrazza.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La fusion tra Giappone e Italia qui funziona davvero: ingredienti italiani con tecnica nipponica.","Tutto il menu e senza glutine: una scelta rara che non compromette la qualita.","La terrazza estiva rende l esperienza ancora piu piacevole."]},
  {n:"Roma Sparita",a:"Piazza di Santa Cecilia 24, Trastevere",pl:3,pr:"€€€ · ~55€",cu:"Romana Tradizionale",tg:"italiana",ws:"https://www.romasparita.eu/",st:"Trattoria romana a Trastevere famosa per la cacio e pepe servita in una cialda di pecorino fritto. Simbolo della cucina capitolina.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La cacio e pepe nella cialda di pecorino e il piatto piu fotografato di Roma: ed e buonissima.","Piazza Santa Cecilia e una delle piu belle di Trastevere.","La cucina romana classica qui e eseguita con rispetto e qualita."]},
  {n:"Roscioli",a:"Via dei Giubbonari 21, Campo de' Fiori",pl:3,pr:"€€€ · ~60€",cu:"Romana Contemporanea",tg:"italiana",ws:"https://www.salumeriaroscioli.com/",st:"Salumeria, forno e ristorante in uno. Carbonara leggendaria, formaggi eccezionali, salumi artigianali. Prenotazione obbligatoria.",mi:{s:0,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["La carbonara di Roscioli e quella contro cui si misurano tutte le altre: perfetta.","Il banco dei formaggi e salumi e tra i migliori d Italia.","Prenotare settimane prima: e uno dei ristoranti piu prenotati d Italia."]},
  {n:"San Baylon",a:"Via di Ripetta 232, Flaminio",pl:3,pr:"€€€ · ~55€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.palazzoripetta.it/en/ristorante/",st:"Nel seicentesco Palazzo Ripetta, ex convento. Cucina italiana contemporanea nella mensa del convento. Corte interna nella bella stagione. Nella guida Michelin.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["L ambientazione nel convento seicentesco e unica: si cena nella storia di Roma.","Cucina italiana contemporanea solida e ben eseguita.","La corte interna e tra i posti piu suggestivi per cenare a Roma."]},
  {n:"Santo Palato",a:"Piazza Tarquinia 4, Appio Latino",pl:2,pr:"€€ · ~38€",cu:"Romana Contemporanea",tg:"italiana",ws:"https://santopalatoroma.com/",st:"Trattoria pop di Sarah Cicolini. Cucina popolare romana con ingredienti di qualita. Tre Gamberi Gambero Rosso. Quinto quarto, coratella.",mi:{s:0,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:16,l:"16/20"},rv:["Sarah Cicolini ha rivoluzionato la trattoria romana: quinto quarto con ingredienti bio.","La coratella di agnello con cipolla e il piatto che ha fatto conoscere Santo Palato al mondo.","Uno dei ristoranti piu importanti della Roma contemporanea."]},
  {n:"Settembrini",a:"Via Luigi Settembrini 25, Prati",pl:3,pr:"€€€ · ~50€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.settembrini.it/",st:"Bistrot contemporaneo nel quartiere Prati, aperto dalla colazione alla sera. Cucina italiana di qualita e ottima selezione di vini.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Dal mattino alla sera: uno dei locali piu versatili e riusciti di Roma.","La cucina italiana e solida e ben eseguita, senza pretese inutili.","Uno dei locali di riferimento del quartiere Prati."]},
  {n:"Sora Lella",a:"Via di Ponte Quattro Capi 16, Trastevere",pl:3,pr:"€€€ · ~55€",cu:"Romana Tradizionale",tg:"italiana",ws:"https://www.soralella.com/",st:"La leggendaria trattoria sull Isola Tiberina, dal 1959. Fondata da Elena Fabrizi sorella di Aldo. Cucina romana classica: cacio e pepe, abbacchio, suppli.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Un istituzione di Roma dal 1959: cucina romana autentica sull unica isola abitata del Tevere.","Fondata dalla sorella di Aldo Fabrizi: la storia e il cibo si intrecciano in modo unico.","La location sull Isola Tiberina e gia da sola un motivo per venire."]},
  {n:"Stendhal",a:"Galleria Alberto Sordi, Centro Storico",pl:3,pr:"€€€ · ~60€",cu:"Milanese Tradizionale",tg:"italiana",ws:"https://www.stendhalmilano.it/",st:"Il primo ristorante milanese di Roma, dentro la Galleria Alberto Sordi. Cucina lombarda classica: risotto giallo, mondeghili, ossobuco, cotoletta. Aperto nel 2024.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Il risotto giallo Milano e i mondeghili tradizionali: cucina milanese autentica nella Capitale.","La location nella Galleria Alberto Sordi e tra le piu belle di Roma.","Un esperimento riuscito: la cucina lombarda funziona benissimo anche a Roma."]},
  {n:"Sushisen",a:"Via Giuseppe Giulietti 21a, Testaccio",pl:3,pr:"€€€ · ~60€",cu:"Giapponese Tradizionale",tg:"giapponese",ws:"https://www.sushisen.it/",st:"Uno dei migliori ristoranti giapponesi d Italia, a Testaccio dal 2004. Chef Yamamoto Eiji. Kaiten sushi, omakase e table experience. Nella guida Michelin.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Il kaiten e una delle rare versioni autentiche in Italia: sushi preparato al momento su nastro rotante.","L omakase dello chef Yamamoto Eiji e un viaggio nella tradizione giapponese di altissimo livello.","Frequentato dalla comunita giapponese di Roma: la garanzia di autenticita piu affidabile."]},
  {n:"Tanuki",a:"Via del Gazometro 40, Ostiense",pl:2,pr:"€€ · ~38€",cu:"Giapponese Izakaya",tg:"giapponese",ws:"https://izakaiatanuki.it/",st:"Izakaya giapponese tradizionale nel quartiere Ostiense. Yakitori, gyoza, tempura e udon. Oltre 40 varieta di sake. Ambiente in stile tatami che ricrea una vera osteria nipponica.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["L ambiente e il piu vicino a una vera izakaya giapponese che si possa trovare a Roma.","La selezione di oltre 40 sake e straordinaria: si trovano etichette rarissime in Italia.","Yakitori e gyoza sono eseguiti con cura e rispetto per la tradizione."]},
  {n:"Trattoria da Cesare",a:"Via del Casaletto 45, Gianicolense",pl:3,pr:"€€€ · ~50€",cu:"Romana Tradizionale",tg:"italiana",ws:"https://www.trattoriadacesare.it/",st:"Trattoria romana classica fuori dal centro, frequentata dai romani. Rigatoni con la pajata, abbacchio al forno con le patate.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["I rigatoni con la pajata sono rari da trovare e qui sono eseguiti in modo impeccabile.","Una trattoria vera dove vengono i romani: il miglior indice di qualita possibile.","Fuori dal centro turistico: si capisce subito perche i romani la amano."]},
  {n:"Trattoria della Stampa",a:"Via della Croce 81, Spagna",pl:2,pr:"€€ · ~38€",cu:"Romana Tradizionale",tg:"italiana",ws:"https://www.trattoriadellastampa.it/",st:"Storica trattoria romana in zona Spagna, frequentata da giornalisti e intellettuali. Cucina laziale tradizionale genuina: cacio e pepe, carbonara, abbacchio.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Una trattoria vera nel cuore della zona Spagna: cucina romana senza compromessi.","I romani di quartiere la frequentano da decenni: la migliore garanzia di qualita.","Atmosfera da trattoria autentica lontana dal turismo di massa."]},
  {n:"Uma Roma",a:"Via Girolamo Benzoni 34, Garbatella",pl:2,pr:"€€ · ~60€",cu:"Italiana Creativa",tg:"italiana",ws:"https://umaroma.com/",st:"Aperto nel 2024. Chef Matteo Taccini e Luigi Senese. Filosofia dell unico: ogni piatto ha un solo ingrediente protagonista. Brace e fermentazione.",mi:{s:0,b:1,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["La riduzione a un solo ingrediente per piatto produce sapori puri e intensi.","Cucina a vista, laboratorio fermentati, materie prime locali: un progetto coerente.","Menu degustazione da 50-70 euro: il miglior rapporto qualita e creativita di Roma."]},
  {n:"Vulcano",a:"Via Flaminia 479, Flaminio",pl:2,pr:"€€ · ~40€",cu:"Pizza Contemporanea",tg:"pizza",ws:"https://www.vulcanopontomilvio.com/",st:"Pizza gourmet di Giuseppe Vesi a Ponte Milvio. Pizze contemporanee, cocktail bar, terrazza panoramica su Ponte Milvio. Aperto dall aperitivo a tarda notte.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La pizza di Vesi e contemporanea e ben eseguita: impasto leggero e ingredienti di qualita.","La terrazza su Ponte Milvio e uno dei posti migliori per una serata estiva a Roma.","Dall aperitivo fino a notte: un format versatile che funziona sempre."]},
  {n:"Zia Restaurant",a:"Via Goffredo Mameli 45, Trastevere",pl:4,pr:"€€€€ · ~110€",cu:"Alta Cucina Creativa",tg:"italiana",ws:"https://www.ziarestaurant.com/",st:"Una stella Michelin e Tre Forchette Gambero Rosso 2026. Chef Antonio Ziantoni. Cucina creativa italiana di grande personalita a Trastevere.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Antonio Ziantoni e uno degli chef piu talentuosi della nuova Roma: cucina precisa e originale.","Il piccione con datteri fermentati e limone confit e tra i piatti piu riusciti.","Tra i pochi che hanno saputo fare una cucina di ricerca autentica a Trastevere."]},
  {n:"Zuma",a:"Via della Fontanella di Borghese 48, Centro Storico",pl:4,pr:"€€€€ · ~100€",cu:"Giapponese Contemporanea",tg:"giapponese",ws:"https://zumarestaurant.com/locations/rome/",st:"Il brand giapponese piu cool al mondo apre a Roma sul roof di Palazzo Fendi. Cucina izakaya contemporanea con robata, sushi e cocktail bar. Terrazza panoramica sui tetti di Roma.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["La terrazza sul Palazzo Fendi e la piu glamour di Roma: vista mozzafiato e cucina di livello.","Il black cod al miso e il signature di Zuma in tutto il mondo: perfetto anche qui.","Cocktail bar tra i piu frequentati del centro: atmosfera unica all imbrunire."]}
];
var favs=new Set(JSON.parse(localStorage.getItem('rmfav25')||'[]'));
var wish=new Set(JSON.parse(localStorage.getItem('rmwish25')||'[]'));
function saveFavs(){localStorage.setItem('rmfav25',JSON.stringify(Array.from(favs)));}
function saveWish(){localStorage.setItem('rmwish25',JSON.stringify(Array.from(wish)));}

window.toggleWish=function(i){
  var n=R[i].n;
  wish.has(n)?wish.delete(n):wish.add(n);
  saveWish();updateWishCount();render();
};

window.toggleFav=function(i){
  var n=R[i].n;
  favs.has(n)?favs.delete(n):favs.add(n);
  saveFavs();document.getElementById('zg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#zg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.z=b.dataset.z;render();});

updateFavCount();render();
};

var S={c:'all',p:'all',g:'all',z:'all',q:'',fav:false};

var mainZones=['centro storico','trastevere','prati','testaccio','parioli','navona','spagna','campo de\' fiori','aventino','celio','flaminio','barberini','repubblica','monteverde','appio latino','gianicolense'];

function getZone(a){return a.split(',').pop().trim().toLowerCase();}

function maps(a){return'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(a+', Roma');}

function miBadge(r){
  if(r.mi.s>=1)return'<span class="sg mi">'+'\u2B50'.repeat(r.mi.s)+' '+(r.mi.s===1?'Una Stella':r.mi.s+' Stelle')+' <span class="gn">Michelin</span></span>';
  if(r.mi.b)return'<span class="sg mi">\uD83D\uDE0A Bib Gourmand <span class="gn">Michelin</span></span>';
  if(r.mi.g)return'<span class="sg mi" style="background:#f0fff4;border-color:#a8d5b5;color:#276749">\uD83C\uDF3F Green Star <span class="gn">Michelin</span></span>';
  return'<span class="sg mi fd">\u2B50 \u2013 <span class="gn">Michelin</span></span>';
}

function makeCard(r,i){
  var isFav=favs.has(r.n);
  var isWish=wish.has(r.n);
  var ta='https://www.tripadvisor.it/Search?q='+encodeURIComponent(r.n+' Roma');
  var rvs='';
  for(var k=0;k<r.rv.length;k++)rvs+='<div class="rv"><span class="st">\u2605\u2605\u2605\u2605\u2605</span><span>'+r.rv[k]+'</span></div>';
  return '<div class="card">'
    +'<button class="favbtn'+(isFav?' on':'')+'" onclick="toggleFav('+i+')">'+( isFav?'\u2764\uFE0F':'\uD83E\uDD0D')+'</button>'
    +'<button class="wishbtn'+(isWish?' on':'')+'" onclick="toggleWish('+i+')">'+( isWish?'\u2705':'\u2714\uFE0F')+'</button>'
    +'<div class="cb">'
    +'<div class="ctag"><span class="ccu">'+r.cu.toUpperCase()+'</span><span class="cpr">'+r.pr+'</span></div>'
    +'<h2 class="cn"><a href="'+r.ws+'" target="_blank" style="color:inherit;text-decoration:none;">'+r.n+'</a></h2>'
    +'<div class="lks">'
    +'<a href="'+maps(r.a)+'" target="_blank">\uD83D\uDCCD '+r.a+'</a>'
    +'<a href="'+r.ws+'" target="_blank" class="ws">\uD83C\uDF10 Sito web</a>'
    +'<a href="https://www.thefork.it/cerca#query='+encodeURIComponent(r.n+' Roma')+'" target="_blank" style="font-size:10px;color:#00813F;font-weight:500;text-decoration:none;border-bottom:1px solid rgba(0,129,63,.3);">\uD83C\uDF74 TheFork</a>'
    +'<a href="'+ta+'" target="_blank" class="ta">\uD83C\uDF7D TripAdvisor</a>'
    +'</div>'
    +'<div class="sc">'+miBadge(r)
    +'<span class="sg gr">'+'\uD83C\uDF74'.repeat(r.gr.f)+' '+r.gr.l+' <span class="gn">Gambero Rosso</span></span>'
    +'<span class="sg es">\u2615 '+r.es.l+' <span class="gn">L\u2019Espresso</span></span>'
    +'</div>'
    +'<p class="cs">'+r.st+'</p>'
    +'<div class="rvs">'+rvs+'</div>'
    +'</div></div>';
}

function updateFavCount(){
  var n=favs.size;
  document.getElementById('favc').textContent=n>0?'('+n+')':'';
}
function updateWishCount(){
  var n=wish.size;
  document.getElementById('wishc').textContent=n>0?'('+n+')':'';
}

function render(){
  var f=[];
  for(var i=0;i<R.length;i++){
    var r=R[i];
    if(S.c!=='all'&&r.tg!==S.c)continue;
    if(S.p!=='all'&&r.pl!==parseInt(S.p))continue;
    if(S.g==='michelin'&&!r.mi.s&&!r.mi.b&&!r.mi.g)continue;
    if(S.g==='gambero'&&r.gr.f<2)continue;
    if(S.g==='espresso'&&r.es.v<15)continue;
    if(S.z!=='all'){var rz=getZone(r.a);if(S.z==='other'){if(mainZones.indexOf(rz)!==-1)continue;}else{if(rz!==S.z)continue;}}
    if(S.wish&&!wish.has(r.n))continue;
    if(S.z!=='all'){var rz=getZone(r.a);if(S.z==='other'){if(mainZones.indexOf(rz)!==-1)continue;}else{if(rz!==S.z)continue;}}
    if(S.fav&&!favs.has(r.n))continue;
    if(S.q){var q=S.q.toLowerCase();var ok=false;var ff=[r.n,r.cu,r.a,r.st];for(var j=0;j<ff.length;j++){if(ff[j].toLowerCase().indexOf(q)>=0){ok=true;break;}}if(!ok)continue;}
    f.push(i);
  }
  document.getElementById('tot').textContent=f.length;
  var rcEl=document.getElementById('rc');if(rcEl)rcEl.textContent=f.length+' risultati';
  var grid=document.getElementById('grid');
  var cards=grid.querySelectorAll('.card');
  for(var k=0;k<cards.length;k++)cards[k].remove();
  document.getElementById('nr').style.display=f.length?'none':'block';
  for(var m=0;m<f.length;m++)grid.insertAdjacentHTML('beforeend',makeCard(R[f[m]],f[m]));
}

document.getElementById('cg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#cg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.c=b.dataset.c;render();});
document.getElementById('pg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#pg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.p=b.dataset.p;render();});
document.getElementById('gg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#gg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.g=b.dataset.g;render();});
document.getElementById('zg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#zg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.z=b.dataset.z;render();});
document.getElementById('favf').addEventListener('click',function(){S.fav=!S.fav;S.wish=false;document.getElementById('wishf').classList.remove('on');this.classList.toggle('on',S.fav);render();});
document.getElementById('wishf').addEventListener('click',function(){S.wish=!S.wish;S.fav=false;document.getElementById('favf').classList.remove('on');this.classList.toggle('on',S.wish);render();});
document.getElementById('srch').addEventListener('input',function(e){S.q=e.target.value;render();});

updateFavCount();
updateWishCount();
render();
