var R=[
  {n:"180g Pizzeria Romana",a:"Via Tor Millina 15, Navona",pl:2,pr:"€€ · ~25€",cu:"Pizza Romana",tg:"pizza",ws:"https://180grammi.it/",st:"La migliore pizza tonda romana di nuova generazione. Impasto a 72 ore, farine artigianali. 50 Top Pizza. Jacopo Mercuro maestro della tonda romana.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["La pizza tonda romana qui raggiunge la sua forma piu compiuta: sottile, croccante, fragrante.","Jacopo Mercuro ha fatto capire a Roma e al mondo cosa puo essere la pizza romana.","Il locale e piccolo ma ben organizzato: la fila scorre veloce."]},
  {n:"Achilli al Parlamento",a:"Via dei Prefetti 15, Centro Storico",pl:4,pr:"€€€€ · ~100€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.enotecaachilli.com/",st:"Una stella Michelin vicino al Parlamento. Enoteca storica trasformata in ristorante d autore. Cucina italiana di territorio con cantina eccezionale.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:16,l:"16/20"},rv:["Enoteca storica con oltre 1000 etichette: un paradiso per gli amanti del vino.","La cucina italiana e solida e rispettosa del territorio: abbinamenti precisi e intelligenti.","La posizione vicino al Pantheon non ha eguali."]},
  {n:"Acquolina",a:"Via dell'Ara Coeli 3, Centro Storico",pl:5,pr:"€€€€€ · ~180€",cu:"Alta Cucina di Mare",tg:"pesce",ws:"https://acquolinaroma.com/",st:"Due stelle Michelin. Chef Daniele Lippi al The First Roma Arte Hotel. Cucina di mare d autore con ingredienti selezionati e tecnica raffinata.",mi:{s:2,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:18,l:"18/20"},rv:["Il crudo di pesce e di una qualita eccezionale: materia prima impeccabile.","Menu degustazione visionario che racconta il mare con poesia e rigore tecnico.","Tra i migliori ristoranti di pesce d Italia."]},
  {n:"All'Oro",a:"Via Giuseppe Pisanelli 25, Prati",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina Creativa",tg:"italiana",ws:"https://ristorantealloro.it/",st:"Una stella Michelin. Chef Riccardo Di Giacinto. Cucina creativa italiana con ingredienti del territorio laziale.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["La carbonara rivisitata e un capolavoro di tecnica e rispetto per la tradizione.","Carta dei vini eccellente, servizio impeccabile.","Tra i migliori indirizzi della Roma contemporanea."]},
  {n:"Aroma",a:"Via Labicana 125, Celio",pl:5,pr:"€€€€€ · ~150€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.aromarestaurant.it/",st:"Una stella Michelin. Sul tetto del Palazzo Manfredi, con vista sul Colosseo. Chef Giuseppe Di Iorio.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["La vista sul Colosseo e unica al mondo: si mangia di fronte al monumento piu famoso di Roma.","Cucina italiana elegante e ben eseguita, degna della location straordinaria.","Il risotto al pecorino con guanciale croccante e uno dei piatti piu riusciti."]},
  {n:"Baccano",a:"Via delle Muratte 23, Fontana di Trevi",pl:3,pr:"€€€ · ~55€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.baccanoroma.com/",st:"Bistrot moderno vicino alla Fontana di Trevi. Cucina italiana contemporanea dalla colazione alla cena, ottima carta dei vini e cocktail bar.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Uno dei pochi posti vicino ai monumenti dove si mangia davvero bene.","La pasta fresca e la charcuterie sono di ottima qualita.","Cocktail bar di livello con bartender preparati."]},
  {n:"Borghese Gallery Restaurant",a:"Viale del Museo Borghese 5, Parioli",pl:4,pr:"€€€€ · ~90€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.borgheserestaurant.com/",st:"Ristorante all'interno della Galleria Borghese. Cucina italiana contemporanea con terrazza sul parco di Villa Borghese.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Mangiare nel parco piu bello di Roma con vista sulla Galleria Borghese: esperienza unica.","La cucina italiana e di buon livello, all altezza della straordinaria location.","Il brunch domenicale e tra i piu esclusivi della citta."]},
  {n:"Checchino dal 1887",a:"Via di Monte Testaccio 30, Testaccio",pl:3,pr:"€€€ · ~65€",cu:"Romana Tradizionale",tg:"italiana",ws:"https://www.checchino-dal-1887.com/",st:"Storico ristorante di cucina romana dal 1887 nel cuore di Testaccio. Coda alla vaccinara, pajata, trippa. Cantina nel Monte Testaccio.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["La coda alla vaccinara e il piatto piu autentico della cucina romana: qui e perfetta.","Cantina leggendaria scavata nel tufo del Monte Testaccio.","Un istituzione di Roma: 140 anni di storia."]},
  {n:"Colline Emiliane",a:"Via degli Avignonesi 22, Barberini",pl:2,pr:"€€ · ~40€",cu:"Emiliana",tg:"italiana",ws:"https://www.collineemiliane.com/",st:"Trattoria emiliana dal 1931 a Roma. Tortellini in brodo fatti a mano, tagliatelle al ragu, cotechino. Artigianato culinario emiliano.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["I tortellini in brodo sono probabilmente i migliori di Roma: pasta tirata a mano ogni giorno.","Una trattoria vera, senza fronzoli, dove si mangia come a Bologna.","Prezzi onesti per una qualita che non teme confronti."]},
  {n:"Da Enzo al 29",a:"Via dei Vascellari 29, Trastevere",pl:2,pr:"€€ · ~35€",cu:"Romana Tradizionale",tg:"italiana",ws:"https://www.daenzoal29.com/",st:"Trattoria romana autentica a Trastevere. Carbonara, cacio e pepe, trippa alla romana. Uno dei posti piu amati dai romani.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La carbonara piu discussa e amata di Roma: crema d uovo densa, guanciale croccante.","Ambiente informale e genuino: ci si siede vicini, si chiacchiera con i vicini.","La lista di attesa vale sempre la pena."]},
  {n:"Dal Bolognese",a:"Piazza del Popolo 1, Flaminio",pl:4,pr:"€€€€ · ~80€",cu:"Emiliana",tg:"italiana",ws:"https://www.dalbolognese.it/",st:"Storico ristorante di cucina bolognese sulla magnifica Piazza del Popolo. Dal 1940, frequentato da artisti e intellettuali.",mi:{s:0,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:15,l:"15/20"},rv:["La terrazza su Piazza del Popolo e una delle location piu belle della ristorazione romana.","La cucina bolognese e eseguita con rispetto e qualita degli ingredienti.","Un pezzo di storia di Roma: Fellini, Warhol, i Berlinguer hanno mangiato qui."]},
  {n:"Enoteca La Torre",a:"Lungotevere delle Armi 22, Prati",pl:5,pr:"€€€€€ · ~170€",cu:"Alta Cucina Creativa",tg:"italiana",ws:"https://www.enotecalatorre.com/",st:"Due stelle Michelin a Villa Laetitia. Chef Domenico Stile. Alta cucina creativa in una villa dei primi del 900 con giardino.",mi:{s:2,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:18,l:"18/20"},rv:["Cucina di ricerca tra le piu interessanti di Roma: ogni piatto e un racconto.","La villa e il giardino creano un atmosfera unica.","Carta dei vini da 3000 etichette: il paradiso per gli appassionati."]},
  {n:"Flavio al Velavevodetto",a:"Via di Monte Testaccio 97, Testaccio",pl:2,pr:"€€ · ~38€",cu:"Romana Tradizionale",tg:"italiana",ws:"https://www.velavevodetto.it/",st:"Osteria romana storica scavata nel Monte Testaccio. Cucina della tradizione capitolina senza compromessi.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["L ambiente e unico: si mangia dentro il Monte Testaccio tra le anfore romane.","La trippa alla romana e gli spaghetti cacio e pepe sono tra i migliori di Roma.","Uno dei luoghi piu autentici della cucina popolare romana."]},
  {n:"Glass Hostaria",a:"Vicolo del Cinque 58, Trastevere",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina Creativa",tg:"italiana",ws:"https://glasshostaria.it/",st:"Una stella Michelin a Trastevere. Chef Cristina Bowerman. Cucina creativa di ricerca in un ambiente di design minimalista.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Cristina Bowerman e una delle chef piu interessanti d Italia: cucina personale e coraggiosa.","Il design dell ambiente e il contrasto piu bello di Trastevere.","Menu degustazione tra i piu originali della scena romana."]},
  {n:"Giulio Passami l'Olio",a:"Via di Monte Giordano 28, Navona",pl:2,pr:"€€ · ~35€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.giuliopassamilolio.it/",st:"Bistrot informale vicino a Piazza Navona. Cucina italiana con ottima selezione di oli extravergine e vini naturali.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Gli oli extravergine sono il filo conduttore di tutta la cucina: una scelta identitaria riuscita.","Vicino a Piazza Navona ma senza essere una trappola per turisti.","Atmosfera informale e prezzi onesti: un posto dove tornare."]},
  {n:"Grano",a:"Piazza Rondanini 53, Centro Storico",pl:3,pr:"€€€ · ~55€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.granoroma.com/",st:"Ristorante contemporaneo vicino al Pantheon. Cucina italiana con ottima selezione di vini naturali e atmosfera informale.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Uno dei pochi posti vicino al Pantheon dove si mangia con qualita senza pagare il conto del turismo.","Vini naturali selezionati con intelligenza, cucina di stagione ben eseguita.","Atmosfera rilassata e conviviale: si torna volentieri."]},
  {n:"Idylio by Apreda",a:"Via della Rotonda 69, Centro Storico",pl:5,pr:"€€€€€ · ~160€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.thepantheonhotel.com/it/ristorante/",st:"Una stella Michelin al The Pantheon Iconic Rome Hotel. Chef Francesco Apreda. Alta cucina italiana con influenze internazionali.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Il risotto ai profumi di Napoli e uno dei piatti signature di Apreda: tecnica impeccabile.","L hotel e una delle dimore piu eleganti di Roma.","Cucina che unisce le radici partenopee dello chef con anni di esperienze internazionali."]},
  {n:"Il Convivio Troiani",a:"Vicolo dei Soldati 31, Navona",pl:5,pr:"€€€€€ · ~140€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.ilconviviotroiani.com/",st:"Una stella Michelin vicino a Piazza Navona. I fratelli Troiani dal 1990. Cucina italiana classica e contemporanea.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["I fratelli Troiani sono una delle famiglie piu importanti della ristorazione romana.","La lombata di agnello laziale con crosta di erbe e il secondo piatto di riferimento.","Cantina straordinaria con verticali di Barolo e Brunello."]},
  {n:"Il Pagliaccio",a:"Via dei Banchi Vecchi 129, Campo de' Fiori",pl:5,pr:"€€€€€ · ~200€",cu:"Alta Cucina Creativa",tg:"italiana",ws:"https://www.ristoranteilpagliaccio.com/",st:"Due stelle Michelin. Chef Anthony Genovese. La cucina piu coraggiosa e sperimentale di Roma con influenze asiatiche.",mi:{s:2,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:19,l:"19/20"},rv:["Anthony Genovese e probabilmente il miglior chef di Roma: cucina che non smette di stupire.","Il menu degustazione e un viaggio tra Europa, Asia e Medio Oriente.","Uno dei ristoranti piu importanti d Italia."]},
  {n:"Il Sorpasso",a:"Via Properzio 31, Prati",pl:2,pr:"€€ · ~32€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.ilsorpassoroma.it/",st:"Bar bistrot di Prati dalla mattina alla sera. Cucina italiana informale di qualita, ottimi panini e taglieri, aperitivo curato.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Dalla colazione alla cena: uno dei locali piu versatili di Roma.","I panini con salumi e formaggi selezionati sono un riferimento nel quartiere Prati.","Ambiente sempre animato e piacevole."]},
  {n:"Imago",a:"Piazza della Trinita dei Monti 6, Spagna",pl:5,pr:"€€€€€ · ~160€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.hotelhasslerroma.com/it/imago",st:"Una stella Michelin all'Hotel Hassler. Chef Andrea Antonini. Terrazza con vista panoramica sui tetti di Roma.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["La vista da Imago e la piu bella di Roma: al tramonto non ha rivali al mondo.","Chef Antonini porta una cucina italiana contemporanea di grande eleganza.","Il risotto alla Romanesca e il piatto che racconta meglio l identita del locale."]},
  {n:"INEO",a:"Piazza della Repubblica 47, Repubblica",pl:5,pr:"€€€€€ · ~150€",cu:"Alta Cucina Creativa",tg:"italiana",ws:"https://www.anantara.com/it/palazzo-naiadi-rome/restaurants/ineo",st:"Una stella Michelin 2026 all'Anantara Palazzo Naiadi. Chef Heros De Agostinis. Alta cucina contemporanea in una location iconica.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Nuova stella Michelin 2026: cucina di grande personalita in un hotel di lusso.","La terrazza con vista sulle Terme di Diocleziano e mozzafiato.","Chef De Agostinis porta un linguaggio gastronomico originale e contemporaneo."]},
  {n:"La Gatta Mangiona",a:"Via Federico Ozanam 30, Monteverde",pl:2,pr:"€€ · ~30€",cu:"Pizza Napoletana",tg:"pizza",ws:"https://www.lagattamangiona.com/",st:"Pizzeria storica di Monteverde. Impasto con lievito madre, farine macinate a pietra. Tra le migliori pizzerie di Roma.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Il cornicione e il piu fragrante di Roma: alveolato, croccante fuori e morbido dentro.","La pizza alla zucca gialla con provola affumicata e insolita e perfetta.","Prenotare con settimane di anticipo: ne vale sempre la pena."]},
  {n:"La Pergola",a:"Via A. Cadlolo 101, Monte Mario",pl:5,pr:"€€€€€ · ~280€",cu:"Alta Cucina Francese",tg:"internazionale",ws:"https://www.romecavalieri.com/la-pergola.html",st:"Tre stelle Michelin. Chef Heinz Beck. Il ristorante piu importante di Roma e uno dei migliori d Italia. Vista panoramica. Cantina da 53000 bottiglie.",mi:{s:3,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:19,l:"19/20"},rv:["L unico tre stelle Michelin di Roma: Heinz Beck e uno dei piu grandi chef d Europa.","La Pasta Ricchi e Poveri ha rivoluzionato la cucina italiana vent anni fa.","La cantina da 53000 bottiglie e la piu importante di un ristorante in Italia."]},
  {n:"La Terrazza Hotel Eden",a:"Via Ludovisi 49, Spagna",pl:5,pr:"€€€€€ · ~150€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.dorchestercollection.com/rome/hotel-eden/restaurants-bars/la-terrazza/",st:"Una stella Michelin 2026 all'Hotel Eden. Chef Salvatore Bianco. Terrazza panoramica sui tetti di Roma.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["La nuova stella Michelin 2026 dell Hotel Eden: panorama tra i piu belli di Roma.","Chef Bianco porta la sua eredita campana in una cucina italiana sofisticata.","Uno degli hotel piu iconici di Roma con una delle terrazze piu suggestive."]},
  {n:"Maccheroni",a:"Piazza delle Coppelle 44, Centro Storico",pl:2,pr:"€€ · ~35€",cu:"Romana Tradizionale",tg:"italiana",ws:"https://www.ristorantemaccheroni.com/",st:"Trattoria romana storica vicino al Pantheon. Cacio e pepe, amatriciana, abbacchio alla romana. Frequentata dai romani.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["L'amatriciana e quella vera: guanciale di Amatrice, pelati San Marzano, pecorino romano.","Un miracolo: cucina autentica a due passi dal Pantheon senza pagare prezzi da turista.","I romani vengono qui: e la migliore raccomandazione possibile."]},
  {n:"Marco Martini Restaurant",a:"Viale Aventino 121, Aventino",pl:5,pr:"€€€€€ · ~120€",cu:"Alta Cucina Creativa",tg:"italiana",ws:"https://www.marcomartinirestaurant.com/",st:"Una stella Michelin sull'Aventino. Chef Marco Martini. Cucina creativa italiana con forti radici laziali.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:16,l:"16/20"},rv:["Marco Martini e uno degli chef piu interessanti della nuova Roma.","Il piccione al ginepro con cicoria e pecorino e il piatto che lo ha reso famoso.","Sull Aventino, lontano dal centro turistico: un indirizzo per intenditori."]},
  {n:"Metamorfosi",a:"Via Giovanni Antonelli 30, Parioli",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina Creativa",tg:"italiana",ws:"https://www.metamorfosiroma.it/",st:"Una stella Michelin ai Parioli. Chef Roy Caceres. Cucina di ricerca con influenze internazionali.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Roy Caceres e uno dei cuochi piu originali di Roma: cucina che si evolve sempre.","Il menu degustazione e una sfida e un piacere: non si sa mai cosa aspettarsi.","Ai Parioli, lontano dal turismo: un indirizzo per chi cerca qualcosa di diverso."]},
  {n:"Moma",a:"Via San Basilio 42, Barberini",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.moma-restaurant.com/",st:"Una stella Michelin vicino a Via Veneto. Chef Salvatore Tassa. Cucina italiana di ricerca con forte identita laziale.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:16,l:"16/20"},rv:["Le castagne di Vallerano e il piatto piu celebre di Salvatore Tassa: semplice e indimenticabile.","Un ristorante che ha saputo costruire una propria identita forte e riconoscibile.","La mise en place essenziale riflette la filosofia del menu: niente di superfluo."]},
  {n:"Orma Roma",a:"Via dei Cerchi 55, Aventino",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.ormarestaurant.it/",st:"Una stella Michelin al Circo Massimo. Chef Roy Caceres. Cucina italiana con influenze colombiane: uno dei ristoranti piu originali di Roma.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Roy Caceres porta un punto di vista colombiano sulla cucina italiana: risultato straordinario.","La vista sul Circo Massimo e unica.","Un ristorante che non assomiglia a nessun altro di Roma."]},
  {n:"Osteria dell'Anima",a:"Via di Santa Maria dell'Anima 26, Navona",pl:3,pr:"€€€ · ~50€",cu:"Romana Contemporanea",tg:"italiana",ws:"https://www.osteriadellanima.it/",st:"Osteria contemporanea vicino a Piazza Navona. Cucina romana rivisitata con materie prime eccellenti e vini naturali.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La cucina romana qui non ha paura di innovare: tradizione e creativita in equilibrio.","Selezione di vini naturali tra le piu curate del centro storico.","Vicino a Piazza Navona ma con prezzi e qualita che non tradiscono."]},
  {n:"Osteria Fernanda",a:"Via Crescenzio 55, Prati",pl:3,pr:"€€€ · ~55€",cu:"Romana Contemporanea",tg:"italiana",ws:"https://www.osteriafernanda.com/",st:"Osteria contemporanea a Prati. Cucina romana aggiornata con ingredienti di qualita e vini naturali.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["La cucina romana contemporanea trova qui uno degli indirizzi piu riusciti.","Vini naturali selezionati con intelligenza: la carta e un viaggio tra piccoli produttori.","Atmosfera informale e piacevole: si torna volentieri."]},
  {n:"Pascucci al Porticciolo",a:"Via Fiumara 2, Fiumicino",pl:4,pr:"€€€€ · ~100€",cu:"Alta Cucina di Mare",tg:"pesce",ws:"https://www.pascucci.it/",st:"Una stella Michelin a Fiumicino. Chef Gianfranco Pascucci. Il miglior ristorante di pesce dell'area romana.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Il miglior pesce dell area romana: Pascucci conosce ogni pescatore del Tirreno.","La zuppa di pesci e crostacei e un patrimonio immateriale della cucina laziale.","Vale il viaggio fino a Fiumicino: uno dei migliori ristoranti di pesce d Italia."]},
  {n:"Per Me Giulio Terrinoni",a:"Vicolo del Malpasso 9, Campo de' Fiori",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina di Mare",tg:"pesce",ws:"https://perme-roma.it/",st:"Una stella Michelin vicino a Campo de Fiori. Chef Giulio Terrinoni. Cucina di mare italiana con tecnica raffinata.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Il crudo di mare e la specialita di Terrinoni: pesce freschissimo con abbinamenti insoliti.","Uno dei migliori ristoranti di pesce di Roma.","L ambiente raccolto crea un intimita perfetta per cene speciali."]},
  {n:"Pianostrada",a:"Via delle Zoccolette 22, Trastevere",pl:2,pr:"€€ · ~38€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.pianostrada.it/",st:"Bistrot contemporaneo a Trastevere, fondato da quattro donne. Cucina italiana con ingredienti bio. Ottima colazione e brunch.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:14,l:"14/20"},rv:["Fondato da quattro donne: una storia di successo nella ristorazione romana.","I dolci e la pasticceria sono di qualita eccezionale: la crostata al limone e leggendaria.","Il brunch del weekend e tra i migliori di Roma."]},
  {n:"Pipero Roma",a:"Corso Vittorio Emanuele II 250, Centro Storico",pl:5,pr:"€€€€€ · ~140€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.piperoroma.it/",st:"Una stella Michelin sul Corso Vittorio Emanuele. Chef Ciro Scamardella. Alessandro Pipero in sala: il miglior maitre d Italia.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Alessandro Pipero e il maitre piu famoso d Italia: l esperienza in sala e straordinaria.","La carbonara di Ciro Scamardella e una delle migliori versioni gourmet esistenti.","Un ristorante che vale per la cucina e per il servizio in egual misura."]},
  {n:"Pizzarium Bonci",a:"Via della Meloria 43, Prati",pl:1,pr:"€ · ~15€",cu:"Pizza al Taglio",tg:"pizza",ws:"https://bonci.it/",st:"La pizza al taglio piu famosa di Roma. Gabriele Bonci. Impasto integrale con lievito madre, topping creativi e ingredienti di eccellenza.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La pizza al taglio piu buona del mondo secondo molti critici: impasto leggero e digeribile.","Gabriele Bonci ha rivoluzionato la pizza al taglio romana.","La fila fuori e spesso lunga: si aspetta, si compra, si mangia in piedi. Ne vale ogni minuto."]},
  {n:"Pulejo",a:"Lungotevere Mellini 11, Prati",pl:5,pr:"€€€€€ · ~120€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.pulejo.com/",st:"Una stella Michelin sul Lungotevere. Chef Francesco Sposito. Cucina italiana contemporanea con radici campane. Terrazza sul Tevere.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["La terrazza sul Tevere e tra le location piu belle della nuova ristorazione romana.","Chef Sposito porta la sua formazione campana in una cucina italiana elegante e moderna.","Un indirizzo giovane e di grande qualita."]},
  {n:"Roma Sparita",a:"Piazza di Santa Cecilia 24, Trastevere",pl:3,pr:"€€€ · ~55€",cu:"Romana Tradizionale",tg:"italiana",ws:"https://www.romasparita.eu/",st:"Trattoria romana a Trastevere famosa per la cacio e pepe servita in una cialda di pecorino fritto. Simbolo della cucina capitolina.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La cacio e pepe nella cialda di pecorino e il piatto piu fotografato di Roma: ed e buonissima.","Piazza Santa Cecilia e una delle piu belle di Trastevere.","La cucina romana classica qui e eseguita con rispetto e qualita."]},
  {n:"Roscioli",a:"Via dei Giubbonari 21, Campo de' Fiori",pl:3,pr:"€€€ · ~60€",cu:"Romana Contemporanea",tg:"italiana",ws:"https://www.salumeriaroscioli.com/",st:"Salumeria, forno e ristorante in uno. Carbonara leggendaria, formaggi eccezionali, salumi artigianali. Prenotazione obbligatoria.",mi:{s:0,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["La carbonara di Roscioli e quella contro cui si misurano tutte le altre: perfetta.","Il banco dei formaggi e salumi e tra i migliori d Italia.","Prenotare settimane prima: e uno dei ristoranti piu prenotati d Italia."]},
  {n:"Santo Palato",a:"Piazza Tarquinia 4, Appio Latino",pl:2,pr:"€€ · ~38€",cu:"Romana Contemporanea",tg:"italiana",ws:"https://santopalatoroma.com/",st:"Trattoria pop di Sarah Cicolini. Cucina popolare romana con ingredienti di qualita. Tre Gamberi Gambero Rosso. Quinto quarto, coratella.",mi:{s:0,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:16,l:"16/20"},rv:["Sarah Cicolini ha rivoluzionato la trattoria romana: quinto quarto con ingredienti bio.","La coratella di agnello con cipolla e il piatto che ha fatto conoscere Santo Palato al mondo.","Uno dei ristoranti piu importanti della Roma contemporanea."]},
  {n:"Settembrini",a:"Via Luigi Settembrini 25, Prati",pl:3,pr:"€€€ · ~50€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.settembrini.it/",st:"Bistrot contemporaneo nel quartiere Prati, aperto dalla colazione alla sera. Cucina italiana di qualita e ottima selezione di vini.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Dal mattino alla sera: uno dei locali piu versatili e riusciti di Roma.","La cucina italiana e solida e ben eseguita, senza pretese inutili.","Uno dei locali di riferimento del quartiere Prati."]},
  {n:"Supplì Roma",a:"Via San Francesco a Ripa 137, Trastevere",pl:1,pr:"€ · ~10€",cu:"Street Food Romano",tg:"italiana",ws:"https://www.suppli.roma.it/",st:"La frittura romana di riferimento. Suppli al telefono, fiori di zucca fritti, baccala in pastella. Qualita degli ingredienti e frittura impeccabile.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Il suppli al telefono e il migliore di Roma: croccante fuori, fondente dentro.","I fiori di zucca fritti con acciuga e baccala sono il secondo piu ordinato.","Una delle esperienze culinarie piu autentiche di Roma."]},
  {n:"Tonnarello",a:"Via della Paglia 1, Trastevere",pl:2,pr:"€€ · ~30€",cu:"Romana Tradizionale",tg:"italiana",ws:"https://www.tonnarello.it/",st:"Trattoria storica di Trastevere con servizio all aperto. Cucina romana classica: cacio e pepe, amatriciana, suppli.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["I tavoli all aperto a Trastevere la sera: un esperienza romana che non tramonta mai.","La cacio e pepe e quella classica, senza sorprese: ed e esattamente quello che si vuole.","Un posto dove i romani portano gli amici che vengono da fuori."]},
  {n:"Trattoria da Cesare",a:"Via del Casaletto 45, Gianicolense",pl:3,pr:"€€€ · ~50€",cu:"Romana Tradizionale",tg:"italiana",ws:"https://www.trattoriadacesare.it/",st:"Trattoria romana classica fuori dal centro, frequentata dai romani. Rigatoni con la pajata, abbacchio al forno con le patate.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["I rigatoni con la pajata sono rari da trovare e qui sono eseguiti in modo impeccabile.","Una trattoria vera dove vengono i romani: il miglior indice di qualita possibile.","Fuori dal centro turistico: si capisce subito perche i romani la amano."]},
  {n:"Zia Restaurant",a:"Via Goffredo Mameli 45, Trastevere",pl:4,pr:"€€€€ · ~110€",cu:"Alta Cucina Creativa",tg:"italiana",ws:"https://www.ziarestaurant.com/",st:"Una stella Michelin e Tre Forchette Gambero Rosso 2026. Chef Antonio Ziantoni. Cucina creativa italiana di grande personalita a Trastevere.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Antonio Ziantoni e uno degli chef piu talentuosi della nuova Roma: cucina precisa e originale.","Il piccione con datteri fermentati e limone confit e tra i piatti piu riusciti.","Tra i pochi che hanno saputo fare una cucina di ricerca autentica a Trastevere."]}
];

var favs=new Set(JSON.parse(localStorage.getItem('rmfav25')||'[]'));
var wish=new Set(JSON.parse(localStorage.getItem('rmwish25')||'[]'));
function saveFavs(){localStorage.setItem('rmfav25',JSON.stringify(Array.from(favs)));}
function saveWish(){localStorage.setItem('rmwish25',JSON.stringify(Array.from(wish)));}

window.toggleWish=function(i){
  var n=R[i].n;
  wish.has(n)?wish.delete(n):wish.add(n);
  saveWish();updateWishCount();render();
};

window.toggleFav=function(i){
  var n=R[i].n;
  favs.has(n)?favs.delete(n):favs.add(n);
  saveFavs();document.getElementById('zg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#zg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.z=b.dataset.z;render();});

updateFavCount();render();
};

var S={c:'all',p:'all',g:'all',z:'all',q:'',fav:false};

var mainZones=['centro storico','trastevere','prati','testaccio','parioli','navona','spagna','campo de\' fiori','aventino','celio','flaminio','barberini','repubblica','monteverde','appio latino','gianicolense'];

function getZone(a){return a.split(',').pop().trim().toLowerCase();}

function maps(a){return'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(a+', Roma');}

function miBadge(r){
  if(r.mi.s>=1)return'<span class="sg mi">'+'\u2B50'.repeat(r.mi.s)+' '+(r.mi.s===1?'Una Stella':r.mi.s+' Stelle')+' <span class="gn">Michelin</span></span>';
  if(r.mi.b)return'<span class="sg mi">\uD83D\uDE0A Bib Gourmand <span class="gn">Michelin</span></span>';
  if(r.mi.g)return'<span class="sg mi" style="background:#f0fff4;border-color:#a8d5b5;color:#276749">\uD83C\uDF3F Green Star <span class="gn">Michelin</span></span>';
  return'<span class="sg mi fd">\u2B50 \u2013 <span class="gn">Michelin</span></span>';
}

function makeCard(r,i){
  var isFav=favs.has(r.n);
  var isWish=wish.has(r.n);
  var ta='https://www.tripadvisor.it/Search?q='+encodeURIComponent(r.n+' Milano');
  var rvs='';
  for(var k=0;k<r.rv.length;k++)rvs+='<div class="rv"><span class="st">\u2605\u2605\u2605\u2605\u2605</span><span>'+r.rv[k]+'</span></div>';
  return '<div class="card">'
    +'<button class="favbtn'+(isFav?' on':'')+'" onclick="toggleFav('+i+')">'+( isFav?'\u2764\uFE0F':'\uD83E\uDD0D')+'</button>'
    +'<button class="wishbtn'+(isWish?' on':'')+'" onclick="toggleWish('+i+')">'+( isWish?'\u2705':'\u2714\uFE0F')+'</button>'
    +'<div class="cb">'
    +'<div class="ctag"><span class="ccu">'+r.cu.toUpperCase()+'</span><span class="cpr">'+r.pr+'</span></div>'
    +'<h2 class="cn"><a href="'+r.ws+'" target="_blank" style="color:inherit;text-decoration:none;">'+r.n+'</a></h2>'
    +'<div class="lks">'
    +'<a href="'+maps(r.a)+'" target="_blank">\uD83D\uDCCD '+r.a+'</a>'
    +'<a href="'+r.ws+'" target="_blank" class="ws">\uD83C\uDF10 Sito web</a>'
    +'<a href="'+ta+'" target="_blank" class="ta">\uD83C\uDF7D TripAdvisor</a>'
    +'</div>'
    +'<div class="sc">'+miBadge(r)
    +'<span class="sg gr">'+'\uD83C\uDF74'.repeat(r.gr.f)+' '+r.gr.l+' <span class="gn">Gambero Rosso</span></span>'
    +'<span class="sg es">\u2615 '+r.es.l+' <span class="gn">L\u2019Espresso</span></span>'
    +'</div>'
    +'<p class="cs">'+r.st+'</p>'
    +'<div class="rvs">'+rvs+'</div>'
    +'</div></div>';
}

function updateFavCount(){
  var n=favs.size;
  document.getElementById('favc').textContent=n>0?'('+n+')':'';
}
function updateWishCount(){
  var n=wish.size;
  document.getElementById('wishc').textContent=n>0?'('+n+')':'';
}

function render(){
  var f=[];
  for(var i=0;i<R.length;i++){
    var r=R[i];
    if(S.c!=='all'&&r.tg!==S.c)continue;
    if(S.p!=='all'&&r.pl!==parseInt(S.p))continue;
    if(S.g==='michelin'&&!r.mi.s&&!r.mi.b&&!r.mi.g)continue;
    if(S.g==='gambero'&&r.gr.f<2)continue;
    if(S.g==='espresso'&&r.es.v<15)continue;
    if(S.z!=='all'){var rz=getZone(r.a);if(S.z==='other'){if(mainZones.indexOf(rz)!==-1)continue;}else{if(rz!==S.z)continue;}}
    if(S.wish&&!wish.has(r.n))continue;
    if(S.z!=='all'){var rz=getZone(r.a);if(S.z==='other'){if(mainZones.indexOf(rz)!==-1)continue;}else{if(rz!==S.z)continue;}}
    if(S.fav&&!favs.has(r.n))continue;
    if(S.q){var q=S.q.toLowerCase();var ok=false;var ff=[r.n,r.cu,r.a,r.st];for(var j=0;j<ff.length;j++){if(ff[j].toLowerCase().indexOf(q)>=0){ok=true;break;}}if(!ok)continue;}
    f.push(i);
  }
  document.getElementById('tot').textContent=f.length;
  var rcEl=document.getElementById('rc');if(rcEl)rcEl.textContent=f.length+' risultati';
  var grid=document.getElementById('grid');
  var cards=grid.querySelectorAll('.card');
  for(var k=0;k<cards.length;k++)cards[k].remove();
  document.getElementById('nr').style.display=f.length?'none':'block';
  for(var m=0;m<f.length;m++)grid.insertAdjacentHTML('beforeend',makeCard(R[f[m]],f[m]));
}

document.getElementById('cg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#cg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.c=b.dataset.c;render();});
document.getElementById('pg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#pg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.p=b.dataset.p;render();});
document.getElementById('gg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#gg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.g=b.dataset.g;render();});
document.getElementById('zg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#zg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.z=b.dataset.z;render();});
document.getElementById('favf').addEventListener('click',function(){S.fav=!S.fav;S.wish=false;document.getElementById('wishf').classList.remove('on');this.classList.toggle('on',S.fav);render();});
document.getElementById('wishf').addEventListener('click',function(){S.wish=!S.wish;S.fav=false;document.getElementById('favf').classList.remove('on');this.classList.toggle('on',S.wish);render();});
document.getElementById('srch').addEventListener('input',function(e){S.q=e.target.value;render();});

updateFavCount();
updateWishCount();
render();
